version: '3.8'

services:
  virtual-store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtual-store
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - grafana-network

networks:
  grafana-network:
    external: true # Red ya creada en mi despliegue de Grafana